// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdfibiqtvvnmkxkswlwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZmliaXF0dnZubWt4a3N3bHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NDU3MjgsImV4cCI6MjA5NDQyMTcyOH0.ZnC35L7qFjXJ51dxQdSMPSxzjdu1P_VStLguDMZfEo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});